In [ ]:
import yfinance as yf
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Análisis fundamental.

## Extracción de la información contable y financiera

Yahoo finance por permite acceder a toda la información que tiene publicada en su página web sobre una empresa. Pero el acceso se realizad con la **programación orientada a objetos (POO)**

`empresa = yf.Ticker(""ITX.MC"")``

`yf.Ticker` es una clase que es como un plantilla y `empresa` es una **instancia y objeto** de esa clase, es decir, un caso concreto creado con la plantilla.

In [ ]:
empresa = yf.Ticker("ITX.MC")
empresa

yfinance.Ticker object <ITX.MC>

`empresa` no es simplemente una variable que contiene un número o una lista. Es un objeto bastante más complejo que contiene:

- Datos y atributos
- Funciones asociadas al propio objeto que denominamos métodos

In [ ]:
print(type(empresa))

<class 'yfinance.ticker.Ticker'>

In [ ]:
dir(empresa)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_analysis',
 '_data',
 '_download_options',
 '_earnings',
 '_earnings_dates',
 '_expirations',
 '_fast_info',
 '_fetch_ticker_tz',
 '_financials',
 '_fundamentals',
 '_funds_data',
 '_get_earnings_dates_using_scrape',
 '_get_earnings_dates_using_screener',
 '_get_ticker_tz',
 '_holders',
 '_isin',
 '_lazy_load_price_history',
 '_message_handler',
 '_news',
 '_options2df',
 '_price_history',
 '_quote',
 '_shares',
 '_tz',
 '_underlying',
 'actions',
 'analyst_price_targets',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'capital_gains',
 'cash_flow',
 'cashflow',
 'dividends',
 'earnings',
 'earnings_dates',
 'earnings_estimate',
 'earnings_history',
 'eps_revisions',
 'eps_trend',
 'fast_info',
 'financials',
 'funds_data',
 'get_actions',
 'get_analyst_price_targets',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_capital_gains',
 'get_cash_flow',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_earnings_dates',
 'get_earnings_estimate',
 'get_earnings_history',
 'get_eps_revisions',
 'get_eps_trend',
 'get_fast_info',
 'get_financials',
 'get_funds_data',
 'get_growth_estimates',
 'get_history_metadata',
 'get_income_stmt',
 'get_incomestmt',
 'get_info',
 'get_insider_purchases',
 'get_insider_roster_holders',
 'get_insider_transactions',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_news',
 'get_recommendations',
 'get_recommendations_summary',
 'get_revenue_estimate',
 'get_sec_filings',
 'get_shares',
 'get_shares_full',
 'get_splits',
 'get_sustainability',
 'get_upgrades_downgrades',
 'growth_estimates',
 'history',
 'history_metadata',
 'income_stmt',
 'incomestmt',
 'info',
 'insider_purchases',
 'insider_roster_holders',
 'insider_transactions',
 'institutional_holders',
 'isin',
 'live',
 'major_holders',
 'mutualfund_holders',
 'news',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cash_flow',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'quarterly_income_stmt',
 'quarterly_incomestmt',
 'recommendations',
 'recommendations_summary',
 'revenue_estimate',
 'sec_filings',
 'session',
 'shares',
 'splits',
 'sustainability',
 'ticker',
 'ttm_cash_flow',
 'ttm_cashflow',
 'ttm_financials',
 'ttm_income_stmt',
 'ttm_incomestmt',
 'upgrades_downgrades',
 'ws']

## CUENTA DE RESULTADOS

In [ ]:
resultados=empresa.income_stmt
resultados

,2026-01-31,2025-01-31,2024-01-31,2023-01-31
Tax Effect Of Unusual Items,-1.503741e+07,-2.669922e+07,-2.254367e+07,-8.498246e+07
Tax Rate For Calcs,2.244390e-01,2.243630e-01,2.147020e-01,2.260170e-01
Normalized EBITDA,1.161200e+10,1.106500e+10,1.014300e+10,8.654000e+09
Total Unusual Items,-6.700000e+07,-1.190000e+08,-1.050000e+08,-3.760000e+08
Total Unusual Items Excluding Goodwill,-6.700000e+07,-1.190000e+08,-1.050000e+08,-3.760000e+08
Net Income From Continuing Operation Net Minority Interest,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Reconciled Depreciation,3.141000e+09,2.997000e+09,2.897000e+09,2.776000e+09
Reconciled Cost Of Revenue,1.664200e+10,1.628800e+10,1.518600e+10,1.401100e+10
EBITDA,1.154500e+10,1.094600e+10,1.003800e+10,8.278000e+09
EBIT,8.390000e+09,7.930000e+09,7.141000e+09,5.502000e+09
Net Interest Income,-3.100000e+07,8.900000e+07,1.090000e+08,-5.900000e+07
Interest Expense,3.700000e+08,3.530000e+08,2.710000e+08,1.440000e+08
Interest Income,3.390000e+08,4.420000e+08,3.800000e+08,8.500000e+07
Normalized Income,6.271963e+09,5.958301e+09,5.463456e+09,4.421018e+09
Net Income From Continuing And Discontinued Operation,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Total Expenses,3.180000e+10,3.095800e+10,2.903400e+10,2.667500e+10
Rent Expense Supplemental,1.085000e+09,1.072000e+09,9.890000e+08,8.590000e+08
Total Operating Income As Reported,7.997000e+09,7.554000e+09,6.809000e+09,5.520000e+09
Diluted Average Shares,3.117794e+09,3.118554e+09,3.117613e+09,3.114630e+09
Basic Average Shares,3.116091e+09,3.114453e+09,3.112837e+09,3.112455e+09
Diluted EPS,1.995000e+00,1.881000e+00,1.726000e+00,1.326000e+00
Basic EPS,1.996000e+00,1.884000e+00,1.729000e+00,1.327000e+00
Diluted NI Availto Com Stockholders,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Net Income Common Stockholders,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Otherunder Preferred Stock Dividend,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Net Income,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09
Minority Interests,0.000000e+00,-1.100000e+07,-1.400000e+07,-1.700000e+07
Net Income Including Noncontrolling Interests,6.220000e+09,5.877000e+09,5.395000e+09,4.147000e+09
Net Income Continuous Operations,6.220000e+09,5.877000e+09,5.395000e+09,4.147000e+09
Tax Provision,1.800000e+09,1.700000e+09,1.475000e+09,1.211000e+09
Pretax Income,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09
Other Non Operating Income Expenses,NaN,NaN,NaN,-2.310000e+08
Special Income Charges,-6.700000e+07,-1.190000e+08,-1.050000e+08,-3.760000e+08
Other Special Charges,6.700000e+07,1.190000e+08,1.050000e+08,3.760000e+08
Impairment Of Capital Assets,4.769900e+07,3.909400e+07,4.748000e+07,NaN
Net Non Operating Interest Income Expense,-3.100000e+07,8.900000e+07,1.090000e+08,-5.900000e+07
Interest Expense Non Operating,3.700000e+08,3.530000e+08,2.710000e+08,1.440000e+08
Interest Income Non Operating,3.390000e+08,4.420000e+08,3.800000e+08,8.500000e+07
Operating Income,8.064000e+09,7.673000e+09,6.914000e+09,5.895000e+09
Operating Expense,1.515800e+10,1.467000e+10,1.384800e+10,1.266400e+10
Other Operating Expenses,1.413000e+09,1.227000e+09,1.246000e+09,1.246000e+09
Depreciation And Amortization In Income Statement,3.155000e+09,3.016000e+09,2.888000e+09,2.701000e+09
Amortization,3.155000e+09,3.016000e+09,2.888000e+09,2.701000e+09
Depreciation Income Statement,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Selling General And Administration,3.591000e+09,3.712000e+09,3.368000e+09,3.105000e+09
Selling And Marketing Expense,3.028000e+09,3.031000e+09,2.733000e+09,2.546000e+09
General And Administrative Expense,5.630000e+08,6.810000e+08,6.350000e+08,5.590000e+08
Rent And Landing Fees,1.085000e+09,1.072000e+09,9.890000e+08,8.590000e+08
Gross Profit,2.322200e+10,2.234300e+10,2.076200e+10,1.855900e+10
Cost Of Revenue,1.664200e+10,1.628800e+10,1.518600e+10,1.401100e+10
Total Revenue,3.986400e+10,3.863200e+10,3.594700e+10,3.256900e+10
Operating Revenue,3.986400e+10,3.863200e+10,3.594700e+10,3.256900e+10

In [ ]:
type(empresa.income_stmt)

pandas.core.frame.DataFrame

In [ ]:
resultados.index

Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Rent Expense Supplemental',
       'Total Operating Income As Reported', 'Diluted Average Shares',
       'Basic Average Shares', 'Diluted EPS', 'Basic EPS',
       'Diluted NI Availto Com Stockholders', 'Net Income Common Stockholders',
       'Otherunder Preferred Stock Dividend', 'Net Income',
       'Minority Interests', 'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Non Operating Income Expenses', 'Special Income Charges',
       'Other Special Charges', 'Impairment Of Capital Assets',
       'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Other Operating Expenses',
       'Depreciation And Amortization In Income Statement', 'Amortization',
       'Depreciation Income Statement', 'Selling General And Administration',
       'Selling And Marketing Expense', 'General And Administrative Expense',
       'Rent And Landing Fees', 'Gross Profit', 'Cost Of Revenue',
       'Total Revenue', 'Operating Revenue'],
      dtype='object')

In [ ]:
orden = [
    "Total Revenue",
    "Cost Of Revenue",
    "Gross Profit",
    "Operating Expense",
    "Operating Income",
    "Interest Expense",
    "Pretax Income",
    "Tax Provision",
    "Net Income"
]

Voy a crear una list comprehension que es una nueva lista que voy a llamar `orden_disponible` en el que guardaremos únicamente las partidas de la lista `orden` que está disponible en `resultados.index`

In [ ]:
orden_disponible = [
    partida for partida in orden
    if partida in resultados.index
]
resultados= resultados.loc[orden_disponible] # seleccionamos las filas que necesitamos.
resultados

                     2026-01-31    2025-01-31    2024-01-31    2023-01-31
Total Revenue      3.986400e+10  3.863200e+10  3.594700e+10  3.256900e+10
Cost Of Revenue    1.664200e+10  1.628800e+10  1.518600e+10  1.401100e+10
Gross Profit       2.322200e+10  2.234300e+10  2.076200e+10  1.855900e+10
Operating Expense  1.515800e+10  1.467000e+10  1.384800e+10  1.266400e+10
Operating Income   8.064000e+09  7.673000e+09  6.914000e+09  5.895000e+09
Interest Expense   3.700000e+08  3.530000e+08  2.710000e+08  1.440000e+08
Pretax Income      8.020000e+09  7.577000e+09  6.870000e+09  5.358000e+09
Tax Provision      1.800000e+09  1.700000e+09  1.475000e+09  1.211000e+09
Net Income         6.220000e+09  5.866000e+09  5.381000e+09  4.130000e+09

In [ ]:
# Utilizamos un diccionario para proceder a la traducción de las partidas contables
traduccion = {
    "Total Revenue": "Ingresos",
    "Cost Of Revenue": "Coste de ventas",
    "Gross Profit": "Margen bruto",
    "Operating Expense": "Gastos operativos",
    "Operating Income": "Resultado operativo",
    "Interest Expense": "Gastos financieros",
    "Pretax Income": "Resultado antes de impuestos",
    "Tax Provision": "Impuestos",
    "Net Income": "Beneficio neto"
}

In [ ]:
resultados_es = resultados.rename(index=traduccion)
resultados_es

,2026-01-31,2025-01-31,2024-01-31,2023-01-31
Ingresos,3.986400e+10,3.863200e+10,3.594700e+10,3.256900e+10
Coste de ventas,1.664200e+10,1.628800e+10,1.518600e+10,1.401100e+10
Margen bruto,2.322200e+10,2.234300e+10,2.076200e+10,1.855900e+10
Gastos operativos,1.515800e+10,1.467000e+10,1.384800e+10,1.266400e+10
Resultado operativo,8.064000e+09,7.673000e+09,6.914000e+09,5.895000e+09
Gastos financieros,3.700000e+08,3.530000e+08,2.710000e+08,1.440000e+08
Resultado antes de impuestos,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09
Impuestos,1.800000e+09,1.700000e+09,1.475000e+09,1.211000e+09
Beneficio neto,6.220000e+09,5.866000e+09,5.381000e+09,4.130000e+09

Extrae el balance con la siguient estructura y lo traduces al español

In [ ]:
orden_balance = [
    "Cash Cash Equivalents And Short Term Investments",
    "Accounts Receivable",
    "Inventory",
    "Current Assets",

    "Net PPE",
    "Goodwill And Other Intangible Assets",
    "Total Assets",

    "Current Liabilities",
    "Long Term Debt",
    "Total Liabilities Net Minority Interest",

    "Stockholders Equity"
]

In [ ]:
balance = empresa.balance_sheet
balance

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Treasury Shares Number,2.852320e+05,1.905846e+06,3.582419e+06,4.932514e+06,NaN
Ordinary Shares Number,3.116367e+09,3.114746e+09,3.113070e+09,3.111719e+09,NaN
Share Issued,3.116652e+09,3.116652e+09,3.116652e+09,3.116652e+09,NaN
Total Debt,6.095000e+09,5.909000e+09,5.739000e+09,5.596000e+09,NaN
Tangible Book Value,1.855500e+10,1.806900e+10,1.722200e+10,1.600500e+10,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,1.096000e+10,1.150200e+10,1.142200e+10,1.008300e+10,NaN
Other Short Term Investments,5.684000e+09,5.120000e+09,4.415000e+09,4.522000e+09,NaN
Cash And Cash Equivalents,5.276000e+09,6.382000e+09,7.007000e+09,5.561000e+09,NaN
Cash Equivalents,2.847000e+09,4.881000e+09,4.621000e+09,3.031000e+09,NaN
Cash Financial,2.429000e+09,1.501000e+09,2.386000e+09,2.530000e+09,NaN

In [ ]:
balance.index

Index(['Treasury Shares Number', 'Ordinary Shares Number', 'Share Issued',
       'Total Debt', 'Tangible Book Value', 'Invested Capital',
       'Working Capital', 'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Minority Interest',
       'Stockholders Equity', 'Treasury Stock', 'Retained Earnings',
       'Additional Paid In Capital', 'Capital Stock', 'Common Stock',
       'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities',
       'Non Current Deferred Taxes Liabilities',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Long Term Provisions', 'Current Liabilities',
       'Other Current Liabilities',
       'Current Debt And Capital Lease Obligation',
       'Current Capital Lease Obligation', 'Current Debt', 'Payables',
       'Other Payable', 'Total Tax Payable', 'Accounts Payable',
       'Total Assets', 'Total Non Current Assets', 'Other Non Current Assets',
       'Non Current Prepaid Assets', 'Non Current Deferred Taxes Assets',
       'Investmentin Financial Assets', 'Held To Maturity Securities',
       'Available For Sale Securities', 'Long Term Equity Investment',
       'Investments In Other Ventures Under Equity Method',
       'Investment Properties', 'Goodwill And Other Intangible Assets',
       'Other Intangible Assets', 'Goodwill', 'Net PPE',
       'Accumulated Depreciation', 'Gross PPE', 'Construction In Progress',
       'Other Properties', 'Machinery Furniture Equipment',
       'Buildings And Improvements', 'Land And Improvements', 'Properties',
       'Current Assets', 'Other Current Assets', 'Hedging Assets Current',
       'Assets Held For Sale Current', 'Inventory', 'Finished Goods',
       'Work In Process', 'Raw Materials', 'Other Receivables',
       'Taxes Receivable', 'Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Equivalents', 'Cash Financial'],
      dtype='object')

In [ ]:
orden_disponible = [
    partida for partida in orden_balance
    if partida in balance.index
]

balance_abreviado = balance.loc[orden_disponible]

balance_abreviado

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Cash Cash Equivalents And Short Term Investments,1.096000e+10,1.150200e+10,1.142200e+10,1.008300e+10,NaN
Accounts Receivable,7.880000e+08,7.460000e+08,6.220000e+08,5.900000e+08,NaN
Inventory,3.249000e+09,3.321000e+09,2.966000e+09,3.191000e+09,NaN
Current Assets,1.569100e+10,1.635600e+10,1.601600e+10,1.463900e+10,NaN
Net PPE,1.667700e+10,1.527400e+10,1.343400e+10,1.250100e+10,NaN
Goodwill And Other Intangible Assets,1.840000e+09,1.607000e+09,1.420000e+09,1.003000e+09,NaN
Total Assets,3.563800e+10,3.471400e+10,3.273500e+10,2.998300e+10,NaN
Current Liabilities,1.017200e+10,1.018700e+10,8.937000e+09,8.137000e+09,NaN
Long Term Debt,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Total Liabilities Net Minority Interest,1.524300e+10,1.503800e+10,1.406300e+10,1.295000e+10,NaN
Stockholders Equity,2.039500e+10,1.967600e+10,1.864200e+10,1.700800e+10,NaN

In [ ]:
traduccion_balance = {
    "Cash Cash Equivalents And Short Term Investments":
        "Efectivo e inversiones a corto plazo",

    "Accounts Receivable":
        "Cuentas a cobrar",

    "Inventory":
        "Existencias",

    "Current Assets":
        "Activo corriente",

    "Net PPE":
        "Inmovilizado material neto",

    "Goodwill And Other Intangible Assets":
        "Fondo de comercio y otros activos intangibles",

    "Total Non Current Assets":
        "Activo no corriente",

    "Total Assets":
        "Activo total",

    "Payables And Accrued Expenses":
        "Proveedores y gastos acumulados",

    "Current Debt":
        "Deuda a corto plazo",

    "Current Liabilities":
        "Pasivo corriente",

    "Long Term Debt":
        "Deuda a largo plazo",

    "Total Non Current Liabilities Net Minority Interest":
        "Pasivo no corriente",

    "Total Liabilities Net Minority Interest":
        "Pasivo total",

    "Stockholders Equity":
        "Patrimonio neto"
}

In [ ]:
balance_abreviado = balance.loc[orden_disponible]

balance_es = balance_abreviado.rename(index=traduccion_balance)
balance_es

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Efectivo e inversiones a corto plazo,1.096000e+10,1.150200e+10,1.142200e+10,1.008300e+10,NaN
Cuentas a cobrar,7.880000e+08,7.460000e+08,6.220000e+08,5.900000e+08,NaN
Existencias,3.249000e+09,3.321000e+09,2.966000e+09,3.191000e+09,NaN
Activo corriente,1.569100e+10,1.635600e+10,1.601600e+10,1.463900e+10,NaN
Inmovilizado material neto,1.667700e+10,1.527400e+10,1.343400e+10,1.250100e+10,NaN
Fondo de comercio y otros activos intangibles,1.840000e+09,1.607000e+09,1.420000e+09,1.003000e+09,NaN
Activo total,3.563800e+10,3.471400e+10,3.273500e+10,2.998300e+10,NaN
Pasivo corriente,1.017200e+10,1.018700e+10,8.937000e+09,8.137000e+09,NaN
Deuda a largo plazo,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Pasivo total,1.524300e+10,1.503800e+10,1.406300e+10,1.295000e+10,NaN
Patrimonio neto,2.039500e+10,1.967600e+10,1.864200e+10,1.700800e+10,NaN

Extrae la informacion del flujo de caja con la siguiente estructura.

In [ ]:
orden_flujos = [
    "Net Income From Continuing Operations",
    "Depreciation And Amortization",
    "Change In Working Capital",
    "Operating Cash Flow",

    "Capital Expenditure",
    "Investing Cash Flow",

    "Issuance Of Debt",
    "Repayment Of Debt",
    "Repurchase Of Capital Stock",
    "Cash Dividends Paid",
    "Financing Cash Flow",

    "Changes In Cash"
]

In [ ]:
cashflow = empresa.cashflow
cashflow

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Free Cash Flow,6.520000e+09,6.616000e+09,6.795000e+09,5.259000e+09,NaN
Repurchase Of Capital Stock,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Repayment Of Debt,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Issuance Of Debt,NaN,NaN,4.000000e+06,NaN,NaN
Capital Expenditure,-2.712000e+09,-2.672000e+09,-1.872000e+09,-1.415000e+09,NaN
End Cash Position,5.276000e+09,6.382000e+09,7.007000e+09,5.561000e+09,NaN
Other Cash Adjustment Outside Changein Cash,NaN,NaN,-1.000000e+06,1.000000e+06,NaN
Beginning Cash Position,6.382000e+09,7.007000e+09,5.561000e+09,7.021000e+09,NaN
Effect Of Exchange Rate Changes,-4.800000e+07,-1.800000e+07,-3.800000e+07,-1.700000e+07,NaN
Changes In Cash,-1.058000e+09,-6.070000e+08,1.485000e+09,-1.444000e+09,NaN
Financing Cash Flow,-7.075000e+09,-6.607000e+09,-5.473000e+09,-4.614000e+09,NaN
Net Other Financing Charges,-1.000000e+06,-1.810057e+09,1.000000e+06,NaN,NaN
Cash Dividends Paid,-5.235000e+09,-4.797000e+09,-3.744000e+09,-2.914000e+09,NaN
Common Stock Dividend Paid,-5.235000e+09,-4.797000e+09,-3.744000e+09,-2.914000e+09,NaN
Net Common Stock Issuance,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Common Stock Payments,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Net Issuance Payments Of Debt,-5.000000e+06,-8.000000e+06,3.000000e+06,-1.800000e+07,NaN
Net Short Term Debt Issuance,-5.000000e+06,-8.000000e+06,4.000000e+06,-1.700000e+07,NaN
Short Term Debt Issuance,NaN,NaN,4.000000e+06,NaN,NaN
Net Long Term Debt Issuance,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Long Term Debt Payments,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Investing Cash Flow,-3.215000e+09,-3.288000e+09,-1.709000e+09,-3.504000e+09,NaN
Net Other Investing Changes,4.000000e+06,5.200000e+07,-5.000000e+06,3.500000e+07,NaN
Net Investment Purchase And Sale,-4.910000e+08,-6.540000e+08,1.680000e+08,-2.124000e+09,NaN
Sale Of Investment,6.000000e+07,5.500000e+07,1.850000e+08,2.700000e+07,NaN
Purchase Of Investment,-5.510000e+08,-7.090000e+08,-1.700000e+07,-2.151000e+09,NaN
Net Business Purchase And Sale,-1.600000e+07,-1.400000e+07,0.000000e+00,NaN,0.0
Purchase Of Business,-1.600000e+07,-1.400000e+07,0.000000e+00,NaN,0.0
Net Intangibles Purchase And Sale,-5.190000e+08,-4.650000e+08,-4.730000e+08,-3.880000e+08,NaN
Purchase Of Intangibles,-5.190000e+08,-4.650000e+08,-4.730000e+08,-3.880000e+08,NaN
Net PPE Purchase And Sale,-2.193000e+09,-2.207000e+09,-1.399000e+09,-1.027000e+09,NaN
Sale Of PPE,NaN,NaN,NaN,NaN,0.0
Purchase Of PPE,-2.193000e+09,-2.207000e+09,-1.399000e+09,-1.027000e+09,NaN
Operating Cash Flow,9.232000e+09,9.288000e+09,8.667000e+09,6.674000e+09,NaN
Taxes Refund Paid,-1.585000e+09,-1.539000e+09,-1.460000e+09,-1.176000e+09,NaN
Change In Working Capital,-8.030000e+08,-1.980000e+08,-5.600000e+07,-6.690000e+08,NaN
Change In Payable,-6.630000e+08,3.920000e+08,1.540000e+08,-4.180000e+08,NaN
Change In Inventory,9.000000e+06,-4.270000e+08,1.300000e+08,-1.930000e+08,NaN
Change In Receivables,-1.490000e+08,-1.640000e+08,-3.410000e+08,-5.800000e+07,NaN
Other Non Cash Items,4.330000e+08,3.530000e+08,3.120000e+08,2.860000e+08,NaN
Provisionand Write Offof Assets,4.800000e+07,3.900000e+07,4.800000e+07,5.300000e+07,NaN
Deferred Tax,NaN,NaN,NaN,NaN,-734000000.0
Depreciation And Amortization,3.141000e+09,2.997000e+09,2.897000e+09,2.776000e+09,NaN
Amortization Cash Flow,5.610000e+08,5.400000e+08,3.860000e+08,3.240000e+08,NaN
Depreciation,2.580000e+09,2.457000e+09,2.511000e+09,2.452000e+09,NaN
Gain Loss On Investment Securities,6.700000e+07,1.190000e+08,1.050000e+08,1.450000e+08,NaN
Net Foreign Currency Exchange Gain Loss,NaN,NaN,NaN,7.000000e+06,NaN
Net Income From Continuing Operations,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09,NaN

In [ ]:
empresa.cashflow.index

Index(['Free Cash Flow', 'Repurchase Of Capital Stock', 'Repayment Of Debt',
       'Issuance Of Debt', 'Capital Expenditure', 'End Cash Position',
       'Other Cash Adjustment Outside Changein Cash',
       'Beginning Cash Position', 'Effect Of Exchange Rate Changes',
       'Changes In Cash', 'Financing Cash Flow', 'Net Other Financing Charges',
       'Cash Dividends Paid', 'Common Stock Dividend Paid',
       'Net Common Stock Issuance', 'Common Stock Payments',
       'Net Issuance Payments Of Debt', 'Net Short Term Debt Issuance',
       'Short Term Debt Issuance', 'Net Long Term Debt Issuance',
       'Long Term Debt Payments', 'Investing Cash Flow',
       'Net Other Investing Changes', 'Net Investment Purchase And Sale',
       'Sale Of Investment', 'Purchase Of Investment',
       'Net Business Purchase And Sale', 'Purchase Of Business',
       'Net Intangibles Purchase And Sale', 'Purchase Of Intangibles',
       'Net PPE Purchase And Sale', 'Sale Of PPE', 'Purchase Of PPE',
       'Operating Cash Flow', 'Taxes Refund Paid', 'Change In Working Capital',
       'Change In Payable', 'Change In Inventory', 'Change In Receivables',
       'Other Non Cash Items', 'Provisionand Write Offof Assets',
       'Deferred Tax', 'Depreciation And Amortization',
       'Amortization Cash Flow', 'Depreciation',
       'Gain Loss On Investment Securities',
       'Net Foreign Currency Exchange Gain Loss',
       'Net Income From Continuing Operations'],
      dtype='object')

In [ ]:
orden_disponible = [
    partida for partida in orden_flujos
    if partida in cashflow.index
]
cashflow = cashflow.loc[orden_disponible]

cashflow

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Net Income From Continuing Operations,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09,NaN
Depreciation And Amortization,3.141000e+09,2.997000e+09,2.897000e+09,2.776000e+09,NaN
Change In Working Capital,-8.030000e+08,-1.980000e+08,-5.600000e+07,-6.690000e+08,NaN
Operating Cash Flow,9.232000e+09,9.288000e+09,8.667000e+09,6.674000e+09,NaN
Capital Expenditure,-2.712000e+09,-2.672000e+09,-1.872000e+09,-1.415000e+09,NaN
Investing Cash Flow,-3.215000e+09,-3.288000e+09,-1.709000e+09,-3.504000e+09,NaN
Issuance Of Debt,NaN,NaN,4.000000e+06,NaN,NaN
Repayment Of Debt,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Repurchase Of Capital Stock,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Cash Dividends Paid,-5.235000e+09,-4.797000e+09,-3.744000e+09,-2.914000e+09,NaN
Financing Cash Flow,-7.075000e+09,-6.607000e+09,-5.473000e+09,-4.614000e+09,NaN
Changes In Cash,-1.058000e+09,-6.070000e+08,1.485000e+09,-1.444000e+09,NaN

In [ ]:
traduccion_flujos = {
    "Net Income": "Beneficio neto",
    "Depreciation And Amortization": "Depreciación y amortización",
    "Change In Working Capital": "Variación del capital circulante",
    "Operating Cash Flow": "Flujo de caja operativo",
    "Capital Expenditure": "Inversión en inmovilizado (CAPEX)",
    "Investing Cash Flow": "Flujo de caja de inversión",
    "Issuance Of Debt": "Emisión de deuda",
    "Repayment Of Debt": "Amortización de deuda",
    "Repurchase Of Capital Stock": "Recompra de acciones",
    "Cash Dividends Paid": "Dividendos pagados",
    "Financing Cash Flow": "Flujo de caja de financiación",
    "Changes In Cash": "Variación neta de efectivo"
}

cashflow_es = cashflow.rename(index=traduccion_flujos)

cashflow_es

,2026-01-31,2025-01-31,2024-01-31,2023-01-31,2022-01-31
Net Income From Continuing Operations,8.020000e+09,7.577000e+09,6.870000e+09,5.358000e+09,NaN
Depreciación y amortización,3.141000e+09,2.997000e+09,2.897000e+09,2.776000e+09,NaN
Variación del capital circulante,-8.030000e+08,-1.980000e+08,-5.600000e+07,-6.690000e+08,NaN
Flujo de caja operativo,9.232000e+09,9.288000e+09,8.667000e+09,6.674000e+09,NaN
Inversión en inmovilizado (CAPEX),-2.712000e+09,-2.672000e+09,-1.872000e+09,-1.415000e+09,NaN
Flujo de caja de inversión,-3.215000e+09,-3.288000e+09,-1.709000e+09,-3.504000e+09,NaN
Emisión de deuda,NaN,NaN,4.000000e+06,NaN,NaN
Amortización de deuda,NaN,0.000000e+00,-1.000000e+06,-1.000000e+06,-5000000.0
Recompra de acciones,NaN,NaN,0.000000e+00,-6.100000e+07,-71000000.0
Dividendos pagados,-5.235000e+09,-4.797000e+09,-3.744000e+09,-2.914000e+09,NaN
Flujo de caja de financiación,-7.075000e+09,-6.607000e+09,-5.473000e+09,-4.614000e+09,NaN
Variación neta de efectivo,-1.058000e+09,-6.070000e+08,1.485000e+09,-1.444000e+09,NaN

# ANÁLISIS DE LA RENTABILIDAD

##Rentabilidad económica

$$ROA=\frac{EBIT}{Activo Total}=\frac{EBIT}{Ventas}\times\frac{Ventas}{Activo Total}$$

In [ ]:
tickers = [
    "ITX.MC",   # Inditex
    "ADS.DE",   # Adidas
    "MC.PA",    # LVMH
    "NKE",      # Nike
    "9983.T",   # Fast Retailing / Uniqlo
    "BOSS.DE"   # Hugo Boss
]

Estima el margen, la rotacion y la rentabilidad economica (ROA) de las empresas. Calcula en primer lugar la de Inditex "ITX.MC"

In [ ]:
empresa = yf.Ticker("ITX.MC")

resultados = empresa.income_stmt
balance = empresa.balance_sheet
cashflow = empresa.cashflow

In [ ]:
ventas = resultados.loc["Total Revenue"].iloc[0]# utilizamos iloc[0] para seleccionar el último ejercicio
EBIT = resultados.loc["EBIT"].iloc[0]
activo_total=balance.loc["Total Assets"].iloc[0]

In [ ]:
margen=EBIT/ventas
rotacion=ventas/activo_total
ROA=EBIT/activo_total

In [ ]:
print(f"El margen de {empresa.ticker} es de {margen:.2f}")
print(f"La rotacion de {empresa.ticker} es de {rotacion:.2f}")
print(f"La rentabilidad economica de {empresa.ticker} es de {ROA:.2f}")

El margen de ITX.MC es de 0.21
La rotacion de ITX.MC es de 1.12
La rentabilidad economica de ITX.MC es de 0.24

**EJERCICIO** Ahora lo calculamos para el resto de empresas del sector para poder compararlas.

In [ ]:
def obtener_datos(ticker):
    empresa = yf.Ticker(ticker)
    resultados = empresa.income_stmt
    balance = empresa.balance_sheet
    cashflow = empresa.cashflow

    ventas = resultados.loc["Total Revenue"].iloc[0]
    EBIT = resultados.loc["Operating Income"].iloc[0]
    activo_total=balance.loc["Total Assets"].iloc[0]

    return ventas, EBIT, activo_total

In [ ]:
datos=[]
for ticker in tickers:
    try:
        ventas, EBIT, activo_total = obtener_datos(ticker)

        datos.append([
            ticker,
            ventas,
            EBIT,
            activo_total
        ])
    except KeyError as e:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Falta la clave: {e}") # Cuando la etiqueta no existe

    except IndexError:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Los datos pueden estar vacíos o incompletos.") #Cuando la posición no existe

In [ ]:
datos

[['ITX.MC',
  np.float64(39864000000.0),
  np.float64(8064000000.0),
  np.float64(35638000000.0)],
 ['ADS.DE',
  np.float64(24811000000.0),
  np.float64(2061000000.0),
  np.float64(20262000000.0)],
 ['MC.PA',
  np.float64(80807000000.0),
  np.float64(17668000000.0),
  np.float64(142037000000.0)],
 ['NKE',
  np.float64(46398000000.0),
  np.float64(3797000000.0),
  np.float64(38410000000.0)],
 ['9983.T',
  np.float64(3400539000000.0),
  np.float64(562561000000.0),
  np.float64(3859353000000.0)],
 ['BOSS.DE',
  np.float64(4269838000.0),
  np.float64(427795000.0),
  np.float64(3721169000.0)]]

In [ ]:
df = pd.DataFrame(
    datos,
    columns=[
        "Ticker",
        "Ventas",
        "EBIT",
        "Activo_total"
    ]
)

df

    Ticker        Ventas          EBIT  Activo_total
0   ITX.MC  3.986400e+10  8.064000e+09  3.563800e+10
1   ADS.DE  2.481100e+10  2.061000e+09  2.026200e+10
2    MC.PA  8.080700e+10  1.766800e+10  1.420370e+11
3      NKE  4.639800e+10  3.797000e+09  3.841000e+10
4   9983.T  3.400539e+12  5.625610e+11  3.859353e+12
5  BOSS.DE  4.269838e+09  4.277950e+08  3.721169e+09

In [ ]:
def ratios(df):
    ratios=pd.DataFrame()
    ratios["Ticker"]=df["Ticker"]
    ratios["Margen_operativo"] = (
        df["EBIT"] / df["Ventas"]
    )
    ratios["Rotación"] = (
        df["Ventas"] / df["Activo_total"]
    )
    ratios["ROA"] = (
    df["EBIT"] / df["Activo_total"]
    )
    return ratios

In [ ]:
ratios=ratios(df)
ratios

    Ticker  Margen_operativo  Rotación       ROA
0   ITX.MC          0.202288  1.118581  0.226275
1   ADS.DE          0.083068  1.224509  0.101718
2    MC.PA          0.218644  0.568915  0.124390
3      NKE          0.081835  1.207967  0.098854
4   9983.T          0.165433  0.881116  0.145766
5  BOSS.DE          0.100190  1.147445  0.114963

Descomponemos la rotación
$$\frac{Ventas}{\text{Activo Total}}=\left\{
\begin{array}{l}
\frac{Ventas}{\text{Activo Corriente}} \\
\frac{Ventas}{\text{Activo No Corriente}}\end{array}
\right.$$

In [ ]:
def obtener_datos(ticker):
    empresa = yf.Ticker(ticker)
    resultados = empresa.income_stmt
    balance = empresa.balance_sheet
    cashflow = empresa.cashflow

    ventas = resultados.loc["Total Revenue"].iloc[0]
    EBIT = resultados.loc["Operating Income"].iloc[0]
    activo_total=balance.loc["Total Assets"].iloc[0]
    activo_corriente = balance.loc["Current Assets"].iloc[0]
    activo_no_corriente = balance.loc["Total Non Current Assets"].iloc[0]


    return ventas, EBIT, activo_total, activo_corriente, activo_no_corriente

In [ ]:
datos=[]
for ticker in tickers:
    try:
        ventas, EBIT, activo_total, activo_corriente, activo_no_corriente = obtener_datos(ticker)

        datos.append([
            ticker,
            ventas,
            EBIT,
            activo_total,
            activo_corriente,
            activo_no_corriente
        ])
    except KeyError as e:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Falta la clave: {e}")

    except IndexError:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Los datos pueden estar vacíos o incompletos.")

In [ ]:
df = pd.DataFrame(
    datos,
    columns=[
        "Ticker",
        "Ventas",
        "EBIT",
        "Activo_total",
        "Activo_corriente",
        "Activo_no_corriente"
    ]
)

df

,Ticker,Ventas,EBIT,Activo_total,Activo_corriente,Activo_no_corriente
0,ITX.MC,3.986400e+10,8.064000e+09,3.563800e+10,1.569100e+10,1.994700e+10
1,ADS.DE,2.481100e+10,2.061000e+09,2.026200e+10,1.197700e+10,8.285000e+09
2,MC.PA,8.080700e+10,1.766800e+10,1.420370e+11,4.817900e+10,9.385800e+10
3,NKE,4.639800e+10,3.797000e+09,3.841000e+10,2.460300e+10,1.380700e+10
4,9983.T,3.400539e+12,5.625610e+11,3.859353e+12,2.527815e+12,1.331538e+12
5,BOSS.DE,4.269838e+09,4.277950e+08,3.721169e+09,1.863044e+09,1.858124e+09

In [ ]:
def ratios(df):
    ratios=pd.DataFrame()
    ratios["Ticker"]=df["Ticker"]
    ratios["Margen_operativo"] = (
        df["EBIT"] / df["Ventas"]
    )
    ratios["Rotación"] = (
        df["Ventas"] / df["Activo_total"]
    )
    ratios["ROA"] = (
    df["EBIT"] / df["Activo_total"]
    )
    ratios["Rotación_corriente"] = (
        df["Ventas"] / df["Activo_corriente"]
    )
    ratios["Rotación_no_corriente"] = (
        df["Ventas"] / df["Activo_no_corriente"]
    )
    return ratios

In [ ]:
ratios=ratios(df)
ratios

,Ticker,Margen_operativo,Rotación,ROA,Rotación_corriente,Rotación_no_corriente
0,ITX.MC,0.202288,1.118581,0.226275,2.540565,1.998496
1,ADS.DE,0.083068,1.224509,0.101718,2.071554,2.994689
2,MC.PA,0.218644,0.568915,0.124390,1.677225,0.860950
3,NKE,0.081835,1.207967,0.098854,1.885868,3.360469
4,9983.T,0.165433,0.881116,0.145766,1.345248,2.553843
5,BOSS.DE,0.100190,1.147445,0.114963,2.291861,2.297930

# ROE

## Rentabilidad Financiera
$$ROE=\frac{\text{Beneficio Neto}}{Patrimonio}$$

## Apalancamiento Financiero

$$ROC=\frac{\text{Beneficio sin Intereses y Después de Impuestos}}{Activo Total}$$

$$ROE=ROC+\left(ROC-k_d(1-\tau)\times \frac{Deuda}{Patrimonio}\right)$$

$$k_d=\frac{Intereses}{Deuda}$$


$$\tau=\frac{Impuestos}{Beneficio Neto}$$

In [ ]:
def obtener_datos_deuda(ticker):
    empresa = yf.Ticker(ticker)
    resultados = empresa.income_stmt
    balance = empresa.balance_sheet
    cashflow = empresa.cashflow


    EBIT = resultados.loc["Operating Income"].iloc[0]
    beneficio_neto = resultados.loc["Net Income"].iloc[0]
    intereses = resultados.loc["Interest Expense"].iloc[0]
    impuestos= resultados.loc["Tax Provision"].iloc[0]
    patrimonio_neto = balance.loc["Stockholders Equity"].iloc[0]
    activo_total=balance.loc["Total Assets"].iloc[0]
    deuda_total = balance.loc["Total Debt"].iloc[0]

    return EBIT, beneficio_neto, patrimonio_neto, activo_total, deuda_total, intereses, impuestos

In [ ]:
datos=[]
for ticker in tickers:
    try:
        EBIT, beneficio_neto, patrimonio_neto, activo_total, deuda_total,intereses, impuestos = obtener_datos_deuda(ticker)

        datos.append([
            ticker,
            EBIT,
            beneficio_neto,
            patrimonio_neto,
            activo_total,
            deuda_total,
            intereses,
            impuestos
        ])
    except KeyError as e:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Falta la clave: {e}")

    except IndexError:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Los datos pueden estar vacíos o incompletos.")

Advertencia: No se pudieron obtener los datos de NKE. Falta la clave: 'Interest Expense'

In [ ]:
datos

[['ITX.MC',
  np.float64(8064000000.0),
  np.float64(6220000000.0),
  np.float64(20395000000.0),
  np.float64(35638000000.0),
  np.float64(6095000000.0),
  np.float64(370000000.0),
  np.float64(1800000000.0)],
 ['ADS.DE',
  np.float64(2061000000.0),
  np.float64(1340000000.0),
  np.float64(5776000000.0),
  np.float64(20262000000.0),
  np.float64(5556000000.0),
  np.float64(228000000.0),
  np.float64(443000000.0)],
 ['MC.PA',
  np.float64(17668000000.0),
  np.float64(10878000000.0),
  np.float64(67472000000.0),
  np.float64(142037000000.0),
  np.float64(36731000000.0),
  np.float64(1151000000.0),
  np.float64(5476000000.0)],
 ['9983.T',
  np.float64(562561000000.0),
  np.float64(433010000000.0),
  np.float64(2273115000000.0),
  np.float64(3859353000000.0),
  np.float64(513500000000.0),
  np.float64(12834000000.0),
  np.float64(191421000000.0)],
 ['BOSS.DE',
  np.float64(427795000.0),
  np.float64(249480000.0),
  np.float64(1537433000.0),
  np.float64(3721169000.0),
  np.float64(1182029000.0),
  np.float64(53116000.0),
  np.float64(85567000.0)]]

In [ ]:
df_deuda = pd.DataFrame(
    datos,
    columns=[
        "Ticker",
        "EBIT",
        "Beneficio_Neto",
        "Patrimonio_Neto",
        "Activo_Total",
        "Deuda_Total",
        "Intereses",
        "Impuestos"
    ]
)

df_deuda

,Ticker,EBIT,Beneficio_Neto,Patrimonio_Neto,Activo_Total,Deuda_Total,Intereses,Impuestos
0,ITX.MC,8.064000e+09,6.220000e+09,2.039500e+10,3.563800e+10,6.095000e+09,3.700000e+08,1.800000e+09
1,ADS.DE,2.061000e+09,1.340000e+09,5.776000e+09,2.026200e+10,5.556000e+09,2.280000e+08,4.430000e+08
2,MC.PA,1.766800e+10,1.087800e+10,6.747200e+10,1.420370e+11,3.673100e+10,1.151000e+09,5.476000e+09
3,9983.T,5.625610e+11,4.330100e+11,2.273115e+12,3.859353e+12,5.135000e+11,1.283400e+10,1.914210e+11
4,BOSS.DE,4.277950e+08,2.494800e+08,1.537433e+09,3.721169e+09,1.182029e+09,5.311600e+07,8.556700e+07

In [ ]:
def ratios_deuda(df):
    ratios=pd.DataFrame()

    ratios["Ticker"]=df["Ticker"]

    ratios["kd"]=df["Intereses"]/df["Deuda_Total"]
    ratios["tau"]=df["Impuestos"]/df["Beneficio_Neto"]


    ratios["ROC"] = (
    df["EBIT"]*(1-ratios["tau"]) / df["Activo_Total"]
    )
    ratios["ROE"] = (
        df["Beneficio_Neto"] / df["Patrimonio_Neto"]
    )
    ratios["Apalancamiento"] = (
        df["Deuda_Total"] / df["Patrimonio_Neto"]
    )
    return ratios

In [ ]:
ratios_deuda=ratios_deuda(df_deuda)
ratios_deuda

    Ticker        kd       tau       ROC       ROE  Apalancamiento
0   ITX.MC  0.060705  0.289389  0.160794  0.304977        0.298848
1   ADS.DE  0.041037  0.330597  0.068090  0.231994        0.961911
2    MC.PA  0.031336  0.503401  0.061772  0.161222        0.544389
3   9983.T  0.024993  0.442071  0.081327  0.190492        0.225901
4  BOSS.DE  0.044936  0.342981  0.075533  0.162270        0.768833

# RATIOS DE MERCADO

$$Price-to-book=\frac{\text{Capitalización Bursatil}}{\text{Patrimonio Neto}}$$


$$PER=\frac{Precio}{\text{Benefcio Neto}}$$

In [ ]:
empresa = yf.Ticker("ITX.MC")

price_to_book = empresa.info.get("priceToBook")
per = empresa.info.get("trailingPE")

print(price_to_book,per)

9.319609 25.93204

Compara el PER y Price to Book entre todas la empresas

In [ ]:
def obtener_datos_mercado (ticker):
    empresa = yf.Ticker(ticker)

    price_to_book = empresa.info.get("priceToBook")
    per = empresa.info.get("trailingPE")

    return price_to_book, per

In [ ]:
datos=[]
for ticker in tickers:
    try:
        price_to_book, per = obtener_datos_mercado (ticker)

        datos.append([
             ticker,
             price_to_book,
             per
        ])
    except KeyError as e:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Falta la clave: {e}")

    except IndexError:
      print(f"Advertencia: No se pudieron obtener los datos de {ticker}. Los datos pueden estar vacíos o incompletos.")

In [ ]:
datos

[['ITX.MC', 9.319609, 25.93204],
 ['ADS.DE', 4.211981, 18.371796],
 ['MC.PA', 2.779226, 17.493162],
 ['NKE', 3.5315244, 16.857143],
 ['9983.T', 8.181746, 46.666924],
 ['BOSS.DE', 1.6283952, 12.066666]]

In [ ]:
df_mercado = pd.DataFrame(
    datos,
    columns=[
        "Ticker",
        "Price to Book",
        "PER"
    ]
)

df_mercado

    Ticker  Price to Book        PER
0   ITX.MC       9.319609  25.932040
1   ADS.DE       4.211981  18.371796
2    MC.PA       2.779226  17.493162
3      NKE       3.531524  16.857143
4   9983.T       8.181746  46.666924
5  BOSS.DE       1.628395  12.066666